"""
Customers_salary_5000_greater
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
from astro.table import Table, Metadata
import pandas as pd
import pendulum

import pandas as pd


@aql.dataframe(task_id="ingest")
def ingest_func():
    employees = "https://gist.githubusercontent.com/kevin336/acbb2271e66c10a5b73aacf82ca82784/raw/e38afe62e088394d61ed30884dd50a6826eee0a8/employees.csv"
    df = pd.read_csv(employees)
    return df

@aql.run_raw_sql(conn_id="duckdb_default", task_id="clean", results_format="pandas_dataframe")
def clean_func(ingest: Table):
    return """
    SELECT * FROM {{ingest}} WHERE salary < 5000
    """

default_args={
    "owner": "Rory Smyth,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2024-03-21", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Rory Smyth": "mailto:rory.smyth@databricks.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/cltzs7j1f01mw01prrs3m6kb0/cloud-ide/cltzs91op01fy01mlueja1yk8/clu18081d03fn01ml0ldpcf9r",
    },
)
def Customers_salary_5000_greater():
    ingest = ingest_func()

    clean = clean_func(
        ingest,
    )

dag_obj = Customers_salary_5000_greater()
