"""
DatabricksPIpeline
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
import pendulum


default_args={
    "owner": "Rory Smyth,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2024-03-21", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Rory Smyth": "mailto:rory.smyth@databricks.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/cltzs7j1f01mw01prrs3m6kb0/cloud-ide/cltzs91op01fy01mlueja1yk8/clu18081d03fn01ml0ldpcf9r",
    },
)
def DatabricksPIpeline():

dag_obj = DatabricksPIpeline()
